### ISSUE TITLE
Complete and adjust webextension features

### ISSUE THREAD

**Issue by insightmind** [insightmind/MORR#43]
# Short Summary

As the basic functionality is now implemented, this issue collects remaining tasks in terms of functionality.

# Tasks

## BackgroundScript

* [x] Increase readability of code
* [x] remove excess functions (merge functions where only a single path exists)
* [ ] do something with the **config** retrieved from main application as soon as defined
* [x] use options_ui declaration in manifest to ensure compatibility with firefox
* [x] remove debug-output

## TabListener

* [ ] As i don't keep a full local copy of all open tabs, i cannot recover the URL in **CloseTabEvents** if the closed tab is not the active one.
* [ ] **SwitchTabEvent** when working with multiple windows is not well-defined (in specs). Currently triggers whenever a different tab gets focus within its window, meaning the *previous* Tab could be of the wrong window.

## DOMEventListener

* [x] The term "Button" for **ButtonClickEvent** is not well defined (it also might never be), requires clarification. (marked as _done_ because because further improvement not requested)
* [x] **TextInputEvent** might not fire based on the websites' implementation of the textfield (might never be fixed). (marked as _done_ because because further improvement not requested)
* [ ] All Events should be tested on the listed research websites
* [x] update **extractTargetAsString** method (DOMEventFactory)
* [x] remove debug-output
* [x] make "TextInput" not trigger for ChangeEvents which are not TextInput-Events (if possible). Issue mainly regards ticking certain checkboxes.

## PostHTTPInterface

* [x] Requires further testing with unreliable Host
* [x] Define top-level protocol

**Comment by Gordin508** [comment]
Closed because remaining tasks are low-priority.
