### ISSUE TITLE
Improve WebBrowserModule

### ISSUE THREAD

**Issue by Gordin508** [insightmind/MORR#66]
# Summary
 Improve the implementation of the webbrowser module in some places.

# Tasks
* [x] move Event-Deserialization to the producers to get rid of evergrowing switch-case in WebExtensionListener
* [x] choose more efficient data-structure for Observers in WebExtensionListener
* [x] refine communication protocol where useful
* [x] make WebExtensionListener stop listening when the windows user logs off (if both users have the same port configured, the second instance could not be launched in this case). Worst possible implementation would be terminating MORR when user changes.

**Comment by sjend** [comment]
MEF appears to not support explicit `[Export]` usage on types already exported by convention. This means, all `IWebBrowserEventObserver` exports currently used to manage the producers internally override the exports of the event queues for outside consumers and need to be removed. Instead explicit `[Import]` with the full producer type should be used.
